version: '3'
services:
  jenkins:
    image: jenkins/jenkins:latest
    container_name: jenkins
    volumes:
      - 'jenkins_volume:/var/jenkins_home'
    restart: unless-stopped
    ports:
      - '8080:8080'
      - '50000:50000'

volumes:
  jenkins_volume:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=172.1.0.14,nolock,soft,rw"
      device: ":/srv/nfs/jenkins"
