# -*- mode: ruby -*-
# vi: set ft=ruby :

# To get the intial admin password, connect to the VM and use:
# sudo cat /var/lib/docker/volumes/nexus-data/_data/admin.password

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/bionic64"
  config.vm.synced_folder "./shared", "/vagrant", type: "virtualbox"

  config.vm.define "logger" do |logger|
    logger.vm.hostname = "logger"
    logger.vm.network "private_network", ip: "172.31.0.11"
    logger.vm.provision "file", source: "shared/prometheus.yml", destination: "/home/vagrant/prometheus.yml"
    logger.vm.provision "file", source: "shared/prometheus.service", destination: "/home/vagrant/prometheus.service"
    logger.vm.provision "shell", :path => "../scripts/puppetagent-ubuntu.sh", :args => "'172.31.0.10' 'logger'"
    # logger.vm.provision "shell", :path => "../scripts/dockerinstall-ubuntu.sh"
    # logger.vm.provision "shell", :path => "../scripts/grafanainstall-docker.sh"
    # logger.vm.provision "shell", :path => "../scripts/prometheusinstall-ubuntu.sh"
  end

  config.vm.provider :virtualbox do |p|
    p.gui = false
    p.customize ["modifyvm", :id, "--memory", 2048]
    p.customize ["modifyvm", :id, "--cpus", 1]
  end

end

