apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-nfs-pv
  labels:
    name: jenkins-nfs-pv # name can be anything
spec:
  storageClassName: nfs-jenkins # same storage class as pvc
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 172.31.0.5 # ip addres of nfs server
    path: '/srv/nfs/jenkins' # path to directory
